In [14]:
import pandas as pd
import zipfile
import os 

dirr = 'Data'

Crypto_dir = os.listdir(dirr+'/Crypto')
Label_dir = os.listdir(dirr+'/Label')

full_crypto_dir = [(dirr+'/Crypto/'+i) for i in Crypto_dir]
full_label_dir = [(dirr+'/Label/'+i) for i in Label_dir]

In [18]:
print(full_crypto_dir)
print(full_label_dir)

['Data/Crypto/BATUSDT.zip', 'Data/Crypto/BTCUSDT.zip', 'Data/Crypto/DOGEUSDT.zip', 'Data/Crypto/DYDXUSDT.zip', 'Data/Crypto/ETCUSDT.zip', 'Data/Crypto/QNTUSDT.zip']
['Data/Label/LABEL_BATUSDT.zip', 'Data/Label/LABEL_BTCUSDT.zip', 'Data/Label/LABEL_DOGEUSDT.zip', 'Data/Label/LABEL_DYDXUSDT.zip', 'Data/Label/LABEL_ETCUSDT.zip', 'Data/Label/LABEL_QNTUSDT.zip']

In [24]:
# #Extract zip file

# for i in range(len(Crypto_dir)):

#     zip_file_path = full_crypto_dir[i]
#     zip_label_path = full_label_dir[i]
#     extract_directory = 'Data/Extracted/'+Crypto_dir[i][:-4]

#     # Open the zip file
#     with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
#         # Extract all the contents to the specified directory
#         zip_ref.extractall(extract_directory+'/Data')
    
#         # Open the zip file
#     with zipfile.ZipFile(zip_label_path, 'r') as zip_ref:
#         # Extract all the contents to the specified directory
#         zip_ref.extractall(extract_directory+'/Label')

In [25]:
Extracted_file = os.listdir('Data/Extracted/')

In [28]:
BTC_data_path = 'Data/Extracted/'+Extracted_file[1]
BTC_data_path

'Data/Extracted/BTCUSDT'

In [30]:
import os
import pyarrow.parquet as pq
import pandas as pd

# Specify the directory containing the Parquet files
directory = 'Data/Extracted/BTCUSDT/Data'

# Get a list of Parquet files in the directory
parquet_files = [file for file in os.listdir(directory) if file.endswith('.parquet')]

# Read and concatenate the Parquet files
data_frames = []
for file in parquet_files:
    file_path = os.path.join(directory, file)
    table = pq.read_table(file_path)
    df = table.to_pandas()
    data_frames.append(df)

# Concatenate the data frames
concatenated_df = pd.concat(data_frames)

# Print the concatenated data frame
concatenated_df

,OPEN,HIGH,LOW,CLOSE,VOLUME,QUOTE_ASSET_VOLUME,NUMBER_OF_TRADES,TAKER_BUY_BASE_ASSET_VOLUME,TAKER_BUY_QUOTE_ASSET_VOLUME,YEAR_AND_MONTH
OPEN_TIME,,,,,,,,,,
1502942400000,4261.48,4280.56,4261.48,4261.48,2.189061,9.333621e+03,9,0.489061,2.089105e+03,201708
1502942700000,4261.48,4261.48,4261.48,4261.48,0.000000,0.000000e+00,0,0.000000,0.000000e+00,201708
1502943000000,4261.48,4261.48,4261.48,4261.48,0.000000,0.000000e+00,0,0.000000,0.000000e+00,201708
1502943300000,4261.48,4264.88,4261.48,4261.48,0.484666,2.065448e+03,9,0.085455,3.642181e+02,201708
1502943600000,4264.88,4266.29,4264.88,4266.29,2.328570,9.931161e+03,11,1.546491,6.595688e+03,201708
...,...,...,...,...,...,...,...,...,...,...
1688020800000,30220.00,30242.00,30219.99,30234.13,54.568400,1.649944e+06,2023,33.647650,1.017363e+06,202306
1688021100000,30234.14,30234.14,30234.13,30234.14,27.471580,8.305795e+05,1564,16.188530,4.894463e+05,202306
1688021400000,30234.13,30241.81,30228.44,30233.17,81.404140,2.461155e+06,1841,27.602330,8.345459e+05,202306
1688021700000,30233.18,30238.00,30220.47,30235.56,68.680630,2.076231e+06,1883,15.014200,4.538837e+05,202306
1688022000000,30235.57,30236.00,30235.56,30236.00,0.445630,1.347388e+04,52,0.415890,1.257467e+04,202306

In [33]:
label_directory = 'Data/Extracted/BTCUSDT/Label'
label_parquet_files = [file for file in os.listdir(label_directory) if file.endswith('.parquet')]
# Read and concatenate the Parquet files
label_data_frames = []
for file in label_parquet_files:
    file_path = os.path.join(label_directory, file)
    table = pq.read_table(file_path)
    df = table.to_pandas()
    label_data_frames.append(df)

# Concatenate the data frames
label_df = pd.concat(label_data_frames)

# Print the concatenated data frame
label_df

               SYMBOL     LABEL
OPEN_TIME
1.505556e+12  BTCUSDT  0.393885
1.505560e+12  BTCUSDT  0.390215
1.505563e+12  BTCUSDT  0.360434
1.505567e+12  BTCUSDT  0.398650
1.505570e+12  BTCUSDT  0.451718
...               ...       ...
1.677611e+12  BTCUSDT  0.448246
1.677614e+12  BTCUSDT  0.470401
1.677618e+12  BTCUSDT  0.468764
1.677622e+12  BTCUSDT  0.474988
1.677625e+12  BTCUSDT  0.484824

[47677 rows x 2 columns]

In [34]:
result = pd.merge(concatenated_df, label_df, on='OPEN_TIME', how='outer')

In [35]:
result

,OPEN,HIGH,LOW,CLOSE,VOLUME,QUOTE_ASSET_VOLUME,NUMBER_OF_TRADES,TAKER_BUY_BASE_ASSET_VOLUME,TAKER_BUY_QUOTE_ASSET_VOLUME,YEAR_AND_MONTH,SYMBOL,LABEL
OPEN_TIME,,,,,,,,,,,,
1.502942e+12,4261.48,4280.56,4261.48,4261.48,2.189061,9333.620962,9.0,0.489061,2089.104962,201708.0,NaN,NaN
1.502943e+12,4261.48,4261.48,4261.48,4261.48,0.000000,0.000000,0.0,0.000000,0.000000,201708.0,NaN,NaN
1.502943e+12,4261.48,4261.48,4261.48,4261.48,0.000000,0.000000,0.0,0.000000,0.000000,201708.0,NaN,NaN
1.502943e+12,4261.48,4264.88,4261.48,4261.48,0.484666,2065.447829,9.0,0.085455,364.218136,201708.0,NaN,NaN
1.502944e+12,4264.88,4266.29,4264.88,4266.29,2.328570,9931.161124,11.0,1.546491,6595.688039,201708.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1.593320e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BTCUSDT,0.435751
1.615000e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BTCUSDT,0.414038
1.618891e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BTCUSDT,0.457853
1.619338e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BTCUSDT,0.499316
1.628834e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BTCUSDT,0.471548

In [38]:
result[(result['LABEL'] > 0) & (result['OPEN'] > 0)]

,OPEN,HIGH,LOW,CLOSE,VOLUME,QUOTE_ASSET_VOLUME,NUMBER_OF_TRADES,TAKER_BUY_BASE_ASSET_VOLUME,TAKER_BUY_QUOTE_ASSET_VOLUME,YEAR_AND_MONTH,SYMBOL,LABEL
OPEN_TIME,,,,,,,,,,,,
1.505556e+12,3753.29,3753.29,3730.00,3730.00,12.426820,4.654148e+04,89.0,0.028936,1.086052e+02,201709.0,BTCUSDT,0.393885
1.505560e+12,3490.00,3599.99,3490.00,3599.99,21.729145,7.725914e+04,68.0,18.714241,6.651942e+04,201709.0,BTCUSDT,0.390215
1.505563e+12,3630.06,3667.99,3630.03,3630.04,3.842747,1.401746e+04,15.0,2.403627,8.793384e+03,201709.0,BTCUSDT,0.360434
1.505567e+12,3610.00,3644.97,3610.00,3630.00,2.445122,8.883551e+03,39.0,1.233507,4.485416e+03,201709.0,BTCUSDT,0.398650
1.505570e+12,3674.98,3727.90,3674.98,3690.00,5.444691,2.010018e+04,92.0,0.792797,2.950498e+03,201709.0,BTCUSDT,0.451718
...,...,...,...,...,...,...,...,...,...,...,...,...
1.677611e+12,23481.63,23492.84,23472.24,23473.37,634.810840,1.490652e+07,27420.0,298.291320,7.004613e+06,202302.0,BTCUSDT,0.448246
1.677614e+12,23263.38,23272.46,23167.15,23189.26,2865.914520,6.652689e+07,66824.0,1252.804130,2.908068e+07,202302.0,BTCUSDT,0.470401
1.677618e+12,23270.59,23277.98,23192.12,23209.65,1829.575030,4.252433e+07,57949.0,867.875200,2.017225e+07,202302.0,BTCUSDT,0.468764
1.677622e+12,23138.89,23173.84,23094.69,23164.41,1371.824500,3.173706e+07,40889.0,703.061520,1.626665e+07,202302.0,BTCUSDT,0.474988
1.677625e+12,23160.47,23161.38,23123.18,23146.11,1263.470880,2.924210e+07,33251.0,671.685600,1.554685e+07,202302.0,BTCUSDT,0.484824